export const labels = {
  policy_id: 'Policy Id',
  customer_id: 'Customer Id',
  fuel: 'Fuel',
  vehicle_segment: 'Vehicle Segment',
  premium: 'Premium',
  bodily_injury_liability: 'Bodily Injury Liability',
  personal_injury_protection: 'Personal Injury Protection',
  property_damage_liability: 'Property Damage Liability',
  collision: 'Collision',
  comprehensive: 'Comprehensive',
  customer_gender: 'Customer Gender',
  customer_income_group: 'Customer Income Group',
  customer_region: 'Customer Region',
  customer_marital_status: 'Customer Marital Status',
  date_of_purchase: 'Date of Purchase',
  policy_purchase_count: 'Number of policies purchased',
  yes: 'Yes',
  no: 'No',
  married: 'Married',
  unmarried: 'Un-Married',
  policy_click_banner_msg: 'Click on any row to edit the policy information.',
  required_field_msg: 'This field is required',
  range_error_msg: '{0} should be in range {1} - {2}',
  mmddyy_date_lbl: 'mm/dd/yyyy',
  male: 'Male',
  female: 'Female',
  others: 'Others',
  cancel: 'Cancel',
  update: 'Update',
  edit_form_heading: 'Edit - (Policy id: {0})',
  select_region_lbl: 'Select Region',
  select_region_error_msg: 'Please select a region',
  search: 'Search',
  policies_chart_header: 'Policies purchased in {0} {1} | Total : {2}'
};
